//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace worklogapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int Id { get; set; }
        public System.DateTime starttime { get; set; }
        public System.DateTime endtime { get; set; }
        public decimal amt { get; set; }
        public int shiftid { get; set; }
        public string description { get; set; }
    
        public virtual shift shift { get; set; }
    }
}
