//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace worklogapi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class work_logEntities : DbContext
    {
        public work_logEntities()
            : base("name=work_logEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<shift> shifts { get; set; }
        public virtual DbSet<task> tasks { get; set; }
    }
}
